# Generated by Django 5.0.4 on 2024-05-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('Name',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='Subject',
        ),
    ]
