# Generated by Django 5.0.4 on 2024-05-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0009_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('order',), 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='documents/', verbose_name='File'),
        ),
    ]
